// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iermkyzsfefzhfqcbnmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllcm1reXpzZmVmemhmcWNibm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDcxMDYsImV4cCI6MjA2Mjc4MzEwNn0.PSHCxZVRQ7wSrfFdqbsOxfi8BQSPQztD5QIPHc9gQDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);